### ISSUE TITLE
package reference violation

### ISSUE THREAD

**Issue by hman-pro** [asc-lab/dotnet-cqrs-intro#1]
https://github.com/asc-lab/dotnet-cqrs-intro/blob/10c5e4fec8902f5990d528f31db449e5cec58569/CqrsWithEs/CqrsWithEs.csproj#L19

please use package reference instead.
`<PackageReference Include="Dapper" Version="1.50.5"/>`

**Comment by witek1902** [comment]
Thank you, fixed.
